name: release

on:
  release:
    types:
      - published

env:
  UV_VERSION: "0.4.22"

jobs:
  build:
    name: Build project for distribution
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}

      - name: Build project for distribution
        run: uv build

      - name: Upload artifact containing distribution files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  pypi:
    name: Publish package distributions to PyPI
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
