on:
  release:
    types:
      - published

name: release

jobs:
  build:
    name: Build project for distribution
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bootstrap Poetry
        run: curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1

      - name: Build project for distribution
        run: poetry build

      - name: Upload artifact containing distribution files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  pypi:
    name: Publish package distributions to PyPI
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
