name: release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: "0.5.16"

jobs:
  build:
    name: Build project for distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Build project for distribution
        run: uv build

      - name: Upload artifact containing distribution files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  pypi:
    name: Publish package distributions to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == "release" && github.event.action == "published"
    environment: release

    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
